namespace: yas-dev

hosts:
  storefront: storefront-dev.yas.local.com
  backoffice: backoffice-dev.yas.local.com
  api: api-dev.yas.local.com
  storefrontAliases: []
  backofficeAliases: []
  apiAliases: []

identity:
  enabled: false
  host: identity.yas.local.com
  serviceHost: keycloak-service.keycloak.svc.cluster.local
  servicePort: 80

mtls:
  mode: STRICT

gateway:
  principals:
    - cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account

services:
  backends:
    - backoffice-bff
    - storefront-bff
    - cart
    - customer
    - inventory
    - location
    - media
    - order
    - payment
    - product
    - search
    - tax
  public:
    - storefront-ui
    - backoffice-ui
    - storefront-bff
    - backoffice-bff
    - swagger-ui
  swaggerService: yas-dev-swagger-ui

timeouts:
  default: 30s
  retryPerTry: 5s

retry:
  attempts: 3
