backend:
  image:
    repository: ghcr.io/nashtech-garage/yas-cart
    tag: latest

  nameOverride: cart
  fullnameOverride: cart
  hostAliases:
    - ip: 10.107.223.248
      hostnames:
        - identity.yas.local.com
  databaseName: cart
  ingress:
    enabled: false
  extraVolumes:
    - name: cart-application-config
      configMap:
        name: cart-application-configmap
  extraVolumeMounts:
    - name: cart-application-config
      mountPath: /opt/yas/cart
  extraApplicationConfigPaths:
    - /opt/yas/cart/cart-application.yaml
