backend:
  image:
    repository: ghcr.io/nashtech-garage/yas-product
    tag: latest

  nameOverride: product
  fullnameOverride: product
  hostAliases:
    - ip: 34.118.233.225
      hostnames:
        - identity.yas.local.com
  databaseName: product
  ingress:
    enabled: false
  extraVolumes:
    - name: product-application-config
      configMap:
        name: product-application-configmap
  extraVolumeMounts:
    - name: product-application-config
      mountPath: /opt/yas/product
  extraApplicationConfigPaths:
    - /opt/yas/product/product-application.yaml  
