backend:
  image:
    repository: ghcr.io/nashtech-garage/yas-search
    tag: latest

  nameOverride: search
  fullnameOverride: search
  hostAliases:
    - ip: 10.107.223.248
      hostnames:
        - identity.yas.local.com
  databaseName: search
  ingress:
    enabled: false
  extraEnvFroms:
    - secretRef:
        name: yas-elasticsearch-credentials-secret
  extraVolumes:
    - name: search-application
      configMap:
        name: search-application-configmap
  extraVolumeMounts:
    - name: search-application
      mountPath: /opt/yas/search
  extraApplicationConfigPaths:
    - /opt/yas/search/search-application.yaml
