apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-addons
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: observability
spec:
  project: default
  source:
    repoURL: https://github.com/ynnhi2607/yas-gitops.git
    targetRevision: main
    path: observability
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
