apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: observability
type: Opaque
stringData:
  username: admin
  password: admin
---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: observability
  labels:
    dashboards: "grafana"
spec:
  external:
    url: http://prometheus-grafana.observability.svc.cluster.local
    adminUser:
      name: grafana-admin-credentials
      key: username
    adminPassword:
      name: grafana-admin-credentials
      key: password
