apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: istio-envoy-sidecars
  namespace: observability
  labels:
    release: prometheus
    app.kubernetes.io/part-of: observability
spec:
  namespaceSelector:
    matchNames:
      - istio-system
      - yas-dev
      - yas-staging
  selector:
    matchExpressions:
      - key: security.istio.io/tlsMode
        operator: Exists
  podMetricsEndpoints:
    - port: http-envoy-prom
      path: /stats/prometheus
      interval: 15s
      relabelings:
        - action: keep
          sourceLabels:
            - __meta_kubernetes_pod_container_name
          regex: istio-proxy
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: istio-control-plane
  namespace: observability
  labels:
    release: prometheus
    app.kubernetes.io/part-of: observability
spec:
  namespaceSelector:
    matchNames:
      - istio-system
  selector:
    matchLabels:
      app: istiod
  podMetricsEndpoints:
    - port: http-monitoring
      path: /metrics
      interval: 15s
