apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - loki.yaml
  - promtail.yaml
  - tempo.yaml
  - opentelemetry-collector.yaml
  - grafana-datasources.yaml
  - grafana-dashboards.yaml
