backend:
  image:
    repository: ghcr.io/nashtech-garage/yas-location
    tag: latest

  nameOverride: location
  fullnameOverride: location
  hostAliases:
    - ip: 10.43.115.244
      hostnames:
        - identity.yas.local.com
  databaseName: location
  ingress:
    enabled: false
