{{- $publicServiceHosts := without .Values.services.public "swagger-ui" }}
{{- $serviceHosts := concat .Values.services.backends $publicServiceHosts (list .Values.services.swaggerService) | uniq }}
{{- range $service := $serviceHosts }}
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: mtls-{{ $service }}
  namespace: {{ $.Values.namespace }}
spec:
  host: "{{ $service }}.{{ $.Values.namespace }}.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
{{- end }}
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: keycloak-no-tls
  namespace: {{ .Values.namespace }}
spec:
  host: keycloak-service.keycloak.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: postgres-no-tls
  namespace: {{ .Values.namespace }}
spec:
  host: "*.postgres.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: DISABLE
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: redis-no-tls
  namespace: {{ .Values.namespace }}
spec:
  host: "*.redis.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: DISABLE
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: kafka-no-tls
  namespace: {{ .Values.namespace }}
spec:
  host: "*.kafka.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: DISABLE
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: elasticsearch-no-tls
  namespace: {{ .Values.namespace }}
spec:
  host: "*.elasticsearch.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: DISABLE
