namespace: yas-dev

hosts:
  storefront: storefront-dev.yas.local.com
  backoffice: backoffice-dev.yas.local.com
  api: api-dev.yas.local.com

identity:
  enabled: true

services:
  swaggerService: yas-dev-swagger-ui
